import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SideNav from '@/components/side-nav';
import Header from '@/components/header';
import { ThemeProvider } from '@/components/theme-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='{inter.className} grid min-h-screen w-full md:grid-cols-[200px_1fr] lg:grid-cols-[280px_1fr]'>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <SideNav />
          <div className='flex flex-col'>
            <Header />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
